[book]
authors = ["Vyacheslav Fedorov"]
language = "ru"
multilingual = false
src = "src"
title = "Разработка и применение программного обеспечения в физических исследованиях"

[output.html]
url = "/physicist-developer-url/"
git-repository-url = "https://github.com/fuodorov/physicist-developer-book"
